#ifndef VIRGL_VAAPI_COMPAT_CORE_FAKE_DRIVER_H
#define VIRGL_VAAPI_COMPAT_CORE_FAKE_DRIVER_H

#include <stdint.h>

#include <va/va.h>

enum {
  VVC_FAKE_SURFACE_I420_THREE_LAYERS = 1,
  VVC_FAKE_SURFACE_I420_TWO_LAYERS = 2,
  VVC_FAKE_SURFACE_FAILING_I420_THREE_LAYERS = 3,
};

#define VVC_FAKE_NON_DRM_MEM_TYPE 0u
#define VVC_FAKE_FAILURE_STATUS VA_STATUS_ERROR_OPERATION_FAILED
#define VVC_FAKE_FAIL_INIT_ENV "VVC_FAKE_FAIL_INIT"

#define VVC_FAKE_LAYER_Y_FORMAT 0x10101010u
#define VVC_FAKE_LAYER_U_FORMAT 0x11111111u
#define VVC_FAKE_LAYER_V_FORMAT 0x22222222u

#define VVC_FAKE_LAYER_Y_OBJECT 0u
#define VVC_FAKE_LAYER_U_OBJECT 1u
#define VVC_FAKE_LAYER_V_OBJECT 2u

#define VVC_FAKE_LAYER_Y_OFFSET 0x1000u
#define VVC_FAKE_LAYER_U_OFFSET 0x2000u
#define VVC_FAKE_LAYER_V_OFFSET 0x3000u

#define VVC_FAKE_LAYER_Y_PITCH 0x0100u
#define VVC_FAKE_LAYER_U_PITCH 0x0200u
#define VVC_FAKE_LAYER_V_PITCH 0x0300u

#endif
